#!/bin/bash

# Stop on failure
set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"


function initrepo {
    ln -s ${REPO_ROOT}/Taskfile ${REPO_ROOT}/.git/hooks/pre-commit
}

function check {
    echo "Run Taskfile help to see other task you can run"
    echo "Running the default precommit checks"
    mypy --strict ${REPO_ROOT}/python/src/*.py
    pytest ${REPO_ROOT}/python/src
    pushd ${REPO_ROOT}/rust
    cargo test
    popd
}

function newday {
    if [ -z "$1" ]; then
        echo "Specify a day"
        return 2
    fi

    NEW_DAY=$1
    echo $NEW_DAY
    touch ${REPO_ROOT}/input/${NEW_DAY}
    touch ${REPO_ROOT}/input/${NEW_DAY}-example
    git add ${REPO_ROOT}/input/${NEW_DAY} ${REPO_ROOT}/input/${NEW_DAY}-example

    # Python
    cp ${REPO_ROOT}/python/src/template.py ${REPO_ROOT}/python/src/${NEW_DAY}.py
    sed -i '' "s/XXX/${NEW_DAY}/" ${REPO_ROOT}/python/src/${NEW_DAY}.py
    git add ${REPO_ROOT}/python/src/${NEW_DAY}.py
    code ${REPO_ROOT}/python/src/${NEW_DAY}.py

    # Rust
    cp ${REPO_ROOT}/rust/src/template.rs ${REPO_ROOT}/rust/src/${NEW_DAY}.rs
    git add ${REPO_ROOT}/rust/src/${NEW_DAY}.rs
    code ${REPO_ROOT}/rust/src/${NEW_DAY}.rs

    code ${REPO_ROOT}/input/${NEW_DAY}
    # Last so that this is the file that has focus
    code ${REPO_ROOT}/input/${NEW_DAY}-example
}

function fmt {
    black python/src
    pushd rust
    cargo fmt
    popd
}

function timeday {
    if [ -z "$1" ]; then
        echo "Specify a day"
        return 2
    fi

    DAY=$1
    pushd ${REPO_ROOT}/python/src
    python3 -m timeit "import ${DAY}; ${DAY}.p1p2('../input/${DAY}')"
    popd
}

function testdays {
    pytest --durations=0 -k test_puzzles ${REPO_ROOT}/python/src
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-check}"